server:
  port: 9090

socket:
  host: localhost
  port: 8890

spring:
  application:
    name: stream-service
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://179.61.188.176:5432/Fen?currentSchema=server&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: postgres
    #schema: classpath:schema.sql
    initialization-mode: always